# v2 syntax
version: '2'

# Named volumes
volumes:
  # PostgreSQL Data
  codecasts-pgsql-data:
    driver: local
  # Redis Data
  codecasts-redis-data:
    driver: local
  # ElasticSearch Data
  codecasts-elastic-data:
    driver: local

services:
  # PHP (with Caddy)
  app:
    image: ambientum/php:7.0-caddy
    container_name: codecasts-php
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - pgsql
      - cache
      - elastic

  # Laravel Queues
  queue:
    image: ambientum/php:7.0
    container_name: codecasts-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - pgsql
      - cache
      - elastic

  # PostgreSQL (9.6)
  pgsql:
    image: ambientum/postgres:9.6
    container_name: codecasts-pgsql
    volumes:
      - codecasts-pgsql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=codecasts
      - POSTGRES_USER=codecasts
      - POSTGRES_PASSWORD=codecasts

  # Redis
  cache:
    image: ambientum/redis:3.2
    container_name: codecasts-redis
    command: --appendonly yes
    volumes:
      - codecasts-redis-data:/data
    ports:
      - "6379:6379"

  # Elastic Search
  elastic:
    image: elasticsearch:2.3
    container_name: codecasts-elastic
    volumes:
      - codecasts-elastic-data:/usr/share/elasticsearch/data
    ports:
     - "9200:9200"
     - "9300:9300"
